DROP DATABASE IF EXISTS TALLER;
CREATE DATABASE  TALLER;
USE TALLER;
CREATE TABLE Coches (
  matricula VARCHAR(8) PRIMARY KEY,
  marca VARCHAR(40) NOT NULL,
  modelo VARCHAR(40) NOT NULL,
  tipo VARCHAR(40) NOT NULL
);

INSERT INTO COCHES (MATRICULA, MARCA, MODELO, TIPO) VALUES
    ('VA2474RF', 'HONDA', 'CIVIC', 'GASOLINA'),
    ('8574CFT', 'MERCEDES', 'BENZ', 'HIBRIDO'),
    ('4754GVS', 'BMW', 'SERIES 3', 'DIESEL');